name: Update ATV Stream

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Requests
        run: pip install requests

      - name: Run Token Script
        run: python atv/token.py

      - name: Create stream.m3u
        run: |
          echo "#EXTM3U" > atv/stream.m3u
          echo "#EXTINF:-1,ATV Avrupa" >> atv/stream.m3u
          cat atv/stream.txt >> atv/stream.m3u

      - name: Commit Updated Playlist
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add atv/stream.m3u atv/stream.txt
          git commit -m "Update ATV stream" || echo "No changes"
          git push
