name: update-stream

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install streamlink

      - name: Get ATV stream
        run: |
          mkdir -p atv

          streamlink \
          --stream-url \
          "https://www.atvavrupa.tv/canli-yayin" \
          best > atv/stream.txt || true

      - name: Create M3U
        run: |
          echo "#EXTM3U" > atv/stream.m3u
          echo '#EXTINF:-1,ATV Avrupa' >> atv/stream.m3u

          if [ -f atv/stream.txt ]; then
            cat atv/stream.txt >> atv/stream.m3u
          fi

      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "Update ATV stream" || echo "No changes"

          git pull --rebase origin main || true

          git push
