name: update-stream

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  update-stream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run ATV script
        run: |
          mkdir -p atv
          python atv/atv_token.py

      - name: Show debug
        run: |
          echo "========== DEBUG =========="
          
          if [ -f atv/debug.txt ]; then
            cat atv/debug.txt
          fi

      - name: Create M3U
        run: |
          echo "#EXTM3U" > atv/stream.m3u
          echo "#EXTINF:-1,ATV Avrupa" >> atv/stream.m3u

          if [ -f atv/stream.txt ]; then
            cat atv/stream.txt >> atv/stream.m3u
          fi

      - name: Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .

          git commit -m "Update ATV stream" || echo "No changes"

          git pull --rebase origin main || true

          git push
