name: CRON TEST

on:
  schedule:
    - cron: '13,23,25,27,29 * * * *'
      timezone: "Europe/Berlin"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cron wurde ausgelöst
        run: |
          echo "======================================"
          echo "CRON TEST"
          echo "======================================"
          echo "Event: ${{ github.event_name }}"
          echo "UTC:"
          date -u
          echo ""
          echo "Hamburg:"
          TZ=Europe/Berlin date
          echo "======================================"
