name: Generate Universal

on:
  workflow_dispatch:
  schedule:
    # alle 30 Minuten, versetzt für stabilere GitHub-Ausführung
    - cron: "27,57 * * * *"
      timezone: "Europe/Berlin"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo
          git checkout "${{ github.event.repository.default_branch }}"

      - name: Install Python + dependencies
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          python3 -m pip install -r repo/requirements.txt

      - name: Run Universal script
        run: |
          cd repo
          export STREAMLINK_PLUGIN_DIR=$(pwd)/src/plugins
          python3 src/universal.py

      - name: Commit & push if file changed
        run: |
          cd repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -f output/universal.m3u8 ]; then
            git add output/universal.m3u8

            if git diff --cached --quiet; then
              echo "No changes to commit"
            else
              git commit -m "Update Universal stream"
              git push origin HEAD
            fi
          else
            echo "No stream file generated → skip commit"
          fi
